Using GL texture for the output
sdk-banuba/OEP_macos pull request #3
Opened 2021-03-24 13:45 UTC by sdk-banuba

2021-03-25 08:36 UTC, dmitrystoyanovsky requested changes

2021-03-25 08:36 UTC, dmitrystoyanovsky commented on offscreen_render_target/src/offscreen_render_target.mm
> +        m_frameSurfaceHandler->set_size_location(glGetUniformLocation(m_program->handle(), "width"),
Use program set_uniform method to configure width & height.

2021-03-25 08:38 UTC, dmitrystoyanovsky commented on offscreen_render_target/src/offscreen_render_target.mm
> +        m_frameSurfaceHandler->set_size_location(glGetUniformLocation(m_program->handle(), "width"),
Additionally, please rename get_pixel_buffer to get_image, move return texture to output configuration parameters...

2021-03-26 08:24 UTC, dmitrystoyanovsky requested changes
Please think to make libraries as modules which can be used by OEP_desktop and OEP_macos.

2021-03-26 08:24 UTC, dmitrystoyanovsky commented on interfaces/offscreen_effect_player.hpp
> +using iort_sptr = std::shared_ptr<bnb::interfaces::offscreen_render_target>;
move this to the end of offscreen_render_target.

2021-03-26 08:24 UTC, dmitrystoyanovsky commented on interfaces/offscreen_effect_player.hpp
> +} // bnb::interfaces
add using for smart_ptr of oep

2021-03-26 08:24 UTC, dmitrystoyanovsky commented on interfaces/offscreen_render_target.hpp
> +         * Example get_image(true)
get_image(true)?

2021-03-26 08:24 UTC, dmitrystoyanovsky commented on interfaces/pixel_buffer.hpp
> +         * Example get_image([](void* cv_pixel_buffer_ref){}, true)
true in example - format

2021-03-26 08:24 UTC, dmitrystoyanovsky commented on interfaces/formats.hpp
> +        texture
add comment what does it mean

2021-03-26 08:24 UTC, dmitrystoyanovsky commented on offscreen_effect_player/include/offscreen_effect_player.hpp
>  using ioep_sptr = std::shared_ptr<bnb::interfaces::offscreen_effect_player>;
move using to interface file

2021-03-26 08:24 UTC, dmitrystoyanovsky commented on offscreen_effect_player/include/offscreen_effect_player.hpp
> -    private:
your constructor is public now, how about friend?

2021-03-26 08:24 UTC, dmitrystoyanovsky commented on interfaces/formats.hpp
> +namespace bnb {
probably it is still interfaces?

2021-03-26 10:27 UTC, dmitrystoyanovsky commented on interfaces/formats.hpp
> +        // CVPixelBufferRef with image on OGL texture
Add: It is useful if you want to avoid GPU-CPU data sync for performance. Please take into the account that on first pixel buffer lock sync will take place, so it is assumed that data will not leave OGL context.

2021-03-26 10:27 UTC, dmitrystoyanovsky commented on interfaces/offscreen_effect_player.hpp
> +using ioep_sptr = std::shared_ptr<bnb::interfaces::offscreen_effect_player>;
leave only sptr for all similar entries

2021-03-26 10:27 UTC, dmitrystoyanovsky commented on offscreen_effect_player/src/offscreen_effect_player.cpp
> +            ort = std::make_shared<bnb::offscreen_render_target>(width, height);
VC asked me provide access for inaccessible constructor since it is private - interesting.

2021-03-29 09:56 UTC, dmitrystoyanovsky approved these changes

2021-03-29 18:01 UTC, bnb-ashershen commented on build/offscreen_effect_player_macos.xcodeproj/xcuserdata/vadim.voloshanov.xcuserdatad/xcschemes/xcschememanagement.plist
>  		<dict>
xcuserdata should be under .gitignore rule

2021-03-29 18:01 UTC, bnb-ashershen approved these changes
xcuserdata

2021-03-31 13:01 UTC, merged